server:
  port: 8080

spring:
  application:
    name: spring-mcp-final

  ai:
    mcp:
      server:
        name: test-mcp-server
        protocol: STATELESS # SSE、STREAMABLE、STATELESS
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        request-timeout: 20s
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
          disallow-delete: false


logging:
  level:
    # 查看MCP详细日志
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE